/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sphintrainbuilder;

import commandgui.commandexecute;
import java.awt.Font;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import loadconfigs.config_file;
import task_workers.task_audio;

/**
 *
 * @author felipe
 */
public class MAINFRAME extends javax.swing.JFrame {

    private config_file configuration_sources;
    private commandexecute process;
    private task_audio player_handler;
    
    /**
     * Creates new form MAINFRAME
     */
    public MAINFRAME() {
        initComponents();
        
                
        jSlider.setMinimum(0);
        jSlider.setMaximum(100); 
        jSlider.setValue(0);
        jSlider.setPaintTicks(true);
        jSlider.setPaintLabels(true);
        jSlider.setBorder(
                BorderFactory.createEmptyBorder(0,0,10,0));
        Font font = new Font("Serif", Font.ITALIC, 15);
        jSlider.setFont(font);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFRP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFPROJNAME = new javax.swing.JTextField();
        jBtnProcessAudio = new javax.swing.JButton();
        jBtnSaveConfig = new javax.swing.JButton();
        jBtnProcessAudio2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTPaneexec = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxListAudioSel = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAudio = new javax.swing.JList<>();
        jSlider = new javax.swing.JSlider();
        jButtonPlayAudio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTPanelResultView = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPHINTRAIN GUI INTERFACE");

        jLabel1.setText("ROOT PATH");

        jLabel2.setText("PROJECT");

        jBtnProcessAudio.setText("PROCESS AUDIO");
        jBtnProcessAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProcessAudioActionPerformed(evt);
            }
        });

        jBtnSaveConfig.setText("SAVE CONFIG");
        jBtnSaveConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveConfigActionPerformed(evt);
            }
        });

        jBtnProcessAudio2.setText("LOAD CONFIG");
        jBtnProcessAudio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProcessAudio2ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTPaneexec);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnProcessAudio, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jBtnSaveConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnProcessAudio2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFRP)
                            .addComponent(jTFPROJNAME, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFRP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPROJNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addComponent(jBtnProcessAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnSaveConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnProcessAudio2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTFPROJNAME, jTFRP});

        jTabbedPane1.addTab("CONFIG", jPanel1);

        jScrollPane1.setViewportView(jListAudio);

        jSlider.setPaintLabels(true);
        jSlider.setPaintTicks(true);
        jSlider.setSnapToTicks(true);
        jSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSliderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });

        jButtonPlayAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/play.png"))); // NOI18N
        jButtonPlayAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayAudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jComboBoxListAudioSel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonPlayAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxListAudioSel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPlayAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("AUDIO", jPanel2);

        jScrollPane4.setViewportView(jTPanelResultView);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("RESULTS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnProcessAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProcessAudioActionPerformed
        // TODO add your handling code here:
        if(configuration_sources == null)
        {
        }
        else
        {
            
            process = new commandexecute(configuration_sources.get_root(),jTPaneexec,jTPanelResultView);
            process.set_config_file(configuration_sources);
            process.start();
        }
    }//GEN-LAST:event_jBtnProcessAudioActionPerformed

    private void jBtnSaveConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveConfigActionPerformed
        // TODO add your handling code here:
        if(configuration_sources == null)
        {
        
        }
        else
            configuration_sources.save_config();
    }//GEN-LAST:event_jBtnSaveConfigActionPerformed

    private void jBtnProcessAudio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProcessAudio2ActionPerformed
        // TODO add your handling code here:
        final JFileChooser chooser = new JFileChooser();
        
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int ret = chooser.showOpenDialog(null);
        
        if (ret == JFileChooser.APPROVE_OPTION)
        {
            File file_local = chooser.getSelectedFile();
            configuration_sources = new config_file(file_local); 
            configuration_sources.load_config();
            
            configuration_sources.build_file_audio(null);
            configuration_sources.build_partial_data();
            
            player_handler = new task_audio( jListAudio,jComboBoxListAudioSel,jButtonPlayAudio,jSlider);
            
            player_handler.set_area_update(configuration_sources.get_array_data());
            player_handler.init_service();
            
            jTFRP.setText(configuration_sources.get_root());
            jTFPROJNAME.setText(configuration_sources.get_proj_name());
        }
        
    }//GEN-LAST:event_jBtnProcessAudio2ActionPerformed

    private void jSliderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderMousePressed
        // TODO add your handling code here:

        if(player_handler == null)
        {

        }
        else if(player_handler.play_worker != null )
        {
            player_handler.play_worker.update_slider(true);
        }

        //System.out.println("MouseEvent.MOUSE_PRESSED");
    }//GEN-LAST:event_jSliderMousePressed

    private void jSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderMouseReleased
        // TODO add your handling code here:
        if(player_handler == null)
        {

        }
        else if(player_handler.play_worker != null )
        {
            player_handler.play_worker.new_slider_position(jSlider.getValue());
            player_handler.play_worker.update_slider(false);
        }

        //System.out.println("MouseEvent.MOUSE_RELEASED");
    }//GEN-LAST:event_jSliderMouseReleased

    private void jButtonPlayAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayAudioActionPerformed
        // TODO add your handling code here:
        if(player_handler == null)
        {

            if(jListAudio.getSelectedIndex() >= 0)
            {
                player_handler.hanlde_audio();
            }
        }else
        {
            if(jListAudio.getSelectedIndex() >= 0)
            {
                player_handler.hanlde_audio();
            }
        }
        
        //System.out.println("button event : play_audio_handler");
    }//GEN-LAST:event_jButtonPlayAudioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK3".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAINFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAINFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAINFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAINFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINFRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnProcessAudio;
    private javax.swing.JButton jBtnProcessAudio2;
    private javax.swing.JButton jBtnSaveConfig;
    private javax.swing.JButton jButtonPlayAudio;
    private javax.swing.JComboBox<String> jComboBoxListAudioSel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListAudio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider;
    private javax.swing.JTextField jTFPROJNAME;
    private javax.swing.JTextField jTFRP;
    private javax.swing.JTextPane jTPaneexec;
    private javax.swing.JTextPane jTPanelResultView;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
